const functions = require("firebase-functions")
const admin = require("firebase-admin")

const express = require("express")
const app = express()

//DURING DEPLOYMENT
// admin.initializeApp()

// DURING LOCAL TESTING
const serviceAccountkey = require("../serviceAccount.json")
admin.initializeApp({
  credential: admin.credential.cert(serviceAccountkey),
  databaseURL: "https://tolet-app-bd.firebaseio.com",
})

// GET ALL RENTALS (FOR SPECIFIC USER or ALL => SEE API DOCS) ORDERED BY LATEST
app.get("/get-all-rentals/", (req, res) => {
  let dbref = admin
    .firestore()
    .collection(`/rentals`)
    .orderBy("createdAt", "desc")

  const userID = req.query.userID

  if (userID) {
    dbref = dbref.where("userID", "==", userID)
  }

  dbref
    .get()
    .then((data) => {
      let rentals = []

      data.forEach((doc) => {
        rentals.push({
          rentalID: doc.id,
          userID: doc.data().userID,
          title: doc.data().title,
          bedrooms: doc.data().bedrooms,
          description: doc.data().description,
          kitchen: doc.data().kitchen,
          size_sqft: doc.data().size_sqft,
          address: doc.data().address,
          washrooms: doc.data().washrooms,
          createdAt: doc.data().createdAt,
          rent: doc.data().rent,
        })
      })

      return res.json(rentals)
    })
    .catch((err) => res.send(err))
})

//CREATE RENTAL FOR A SPECIFIC USER USING USER ID GENERATED BY FIREBASE
app.post("/create-rental", (req, res) => {
  const newRental = {
    userID: req.body.userID,
    title: req.body.title,
    description: req.body.description,
    bedrooms: req.body.bedrooms,
    kitchen: req.body.kitchen,
    washrooms: req.body.washrooms,
    diningrooms: req.body.diningrooms,
    rent: req.body.rent,
    size_sqft: req.body.size_sqft,
    address: req.body.address,
    createdAt: new Date().toISOString(),
  }

  admin
    .firestore()
    .collection(`/rentals`)
    .add(newRental)
    .then((doc) => {
      res.send({ message: `document ${doc.id} created successfully` })
    })
    .catch((err) => {
      res.status(500).json({ error: "something went wrong" })
      console.log(err)
    })
})

exports.api = functions.https.onRequest(app)
